import type { Metadata } from 'next'
import { Roboto_Flex } from 'next/font/google'
import './globals.css'

const roboto = Roboto_Flex({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-gray-900 text-gray-100`}>
        {children}
      </body>
    </html>
  )
}
